apps/clientsocialnetworks/urls.py
from . import views
from django.urls import path


app_name = "clientsocialnetworks"

urlpatterns = [
    path('', views.list_clientsocialnetwork, name='list_clientsocialnetwork'),
    path('adicionar/', views.add_clientsocialnetwork, name='add_clientsocialnetwork'),
    path('editar/<int:id_clientsocialnetwork>/', views.edit_clientsocialnetwork, name='edit_clientsocialnetwork'),
    path('excluir/<int:id_clientsocialnetwork>/', views.delete_clientsocialnetwork, name='delete_clientsocialnetwork'),
]

modeloapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("categorias/", include("categories.urls", namespace="categories")),
    path("produtos/", include("product.urls", namespace="products")),
    path("clientes/", include("clients.urls", namespace="clients")),
    path("pedidos/", include("order.urls", namespace="orders")),
    path('socialnetworks/', include('socialnetworks.urls', namespace="socialnetworks")),
    path('clientsocialnetworks/', include('clientsocialnetworks.urls', namespace="clientsocialnetworks")),
    path('orderitems/', include('orderitems.urls', namespace="orderitems")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientsocialnetworks/models.py
from django.db import models
from socialnetworks.models import SocialNetwork
from clients.models import Client

# Create your models here.

class ClientSocialNetwork(models.Model):
     
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    socialnetwork = models.ForeignKey(SocialNetwork, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Cliente Rede Social'
        verbose_name_plural = 'Cliente Redes Sociais'
        #ordering =['-client__id']

apps/clientsocialnetworks/forms.py
from django import forms
from clientsocialnetworks.models import ClientSocialNetwork


class ClientSocialNetworkForm(forms.ModelForm):

    class Meta:
        model = ClientSocialNetwork
        exclude = ()

apps/clientsocialnetworks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from clientsocialnetworks.models import ClientSocialNetwork
from clientsocialnetworks.forms import ClientSocialNetworkForm

def add_clientsocialnetwork(request):
    template_name = 'clientsocialnetworks/add_clientsocialnetwork.html'
    context = {}
    if request.method == 'POST':
        form = ClientSocialNetworkForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('clientsocialnetworks:list_clientsocialnetwork')
    form = ClientSocialNetworkForm()
    context['form'] = form
    return render(request, template_name, context)

def list_clientsocialnetwork(request):
    template_name = "clientsocialnetworks/list_clientsocialnetwork.html"
    clientsocialnetwork = ClientSocialNetwork.objects.filter()
    context = {"clientsocialnetwork": clientsocialnetwork}
    return render(request, template_name, context)

def edit_clientsocialnetwork(request, id_clientsocialnetwork):
    template_name = 'clientsocialnetworks/add_clientsocialnetwork.html'
    context = {}
    csn = get_object_or_404(ClientSocialNetwork, id=id_clientsocialnetwork)

    if request.method == 'POST':
        form = ClientSocialNetworkForm(request.POST, instance=csn)
        if form.is_valid():
            form.save()
            return redirect('clientsocialnetworks:list_clientsocialnetwork')
    form = ClientSocialNetworkForm(instance=csn)
    context['form'] = form
    return render(request, template_name, context)

def delete_clientsocialnetwork(request, id_clientsocialnetwork):
    csn = get_object_or_404(ClientSocialNetwork, id=id_clientsocialnetwork)
    csn.delete()
    return redirect('clientsocialnetworks:list_clientsocialnetwork')

templates/clientsocialnetworks/add_clientsocialnetwork.html
{% extends 'base.html' %}

{% block title %}
  Adicionar Cliente x Rede Social - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
  <b>Cadastro de Cliente x Rede Social</b>
  <br />
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    <label>Cliente:</label>
    <br />
    {{ form.client }}
    <br />
    <br />
    <label>Rede Social:</label>
    <br />
    {{ form.socialnetwork }}
    <br />
    <br />
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientsocialnetworks/list_clientsocialnetwork.html
{% extends 'base.html' %}

{% block title %}
  Lista de Clientes em Redes Sociais - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
  <a href="{% url 'clientsocialnetworks:add_clientsocialnetwork' %}">Cadastro de novo Cliente em Rede Social</a>
  <br />
  <br />
  <b>Lista de Clientes em Redes Sociais</b>
  <br />
  <br />
  <table border="1">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Cliente</th>
        <th scope="col">Rede Social</th>
        <th scope="col">Editar</th>
        <th scope="col">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for item in clientsocialnetwork %}
        <tr>
          <th>{{ item.id }}</th>
          <td>{{ item.client }}</td>
          <td>{{ item.socialnetwork }}</td>
          <td>
            <a href="{% url 'clientsocialnetworks:edit_clientsocialnetwork' item.id %}">Editar</a>
          </td>
          <td>
            <a href="{% url 'clientsocialnetworks:delete_clientsocialnetwork' item.id %}">Excluir</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}