apps/categories/urls.py
from django.urls import path
from . import views

app_name = "categories"

urlpatterns = [
    path("adicionar/", views.add_Category, name="add_category"),
    path("", views.list_categories, name="list_categories"),
    path("editar/<int:id_category>/", views.edit_category, name="edit_category"),
    path("excluir/<int:id_category>/", views.delete_category, name="delete_category"),
]

modeloapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("categorias/", include("categories.urls", namespace="categories")),
    path("produtos/", include("product.urls", namespace="products")),
    path("clientes/", include("clients.urls", namespace="clients")),
    path("pedidos/", include("order.urls", namespace="orders")),
    path('socialnetworks/', include('socialnetworks.urls', namespace="socialnetworks")),
    path('clientsocialnetworks/', include('clientsocialnetworks.urls', namespace="clientsocialnetworks")),
    path('orderitems/', include('orderitems.urls', namespace="orderitems")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/categories/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField("Nome", max_length=50)
    description = models.TextField("Descricao", max_length=100)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["id"]

    def __str__(self):
        return self.name

apps/categories/forms.py
from django import forms
from .models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ()

apps/categories/views.py
from django.shortcuts import render, redirect
from .forms import CategoryForm
from .models import Category, models
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.


def add_Category(request):
    template_name = "categories/add_category.html"
    context = {}
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():  # Corrigido o erro aqui
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect(
                "categories:list_categories"
            )  # Corrigido o nome da URL aqui
    form = CategoryForm()
    context["form"] = form
    return render(request, template_name, context)


def list_categories(request):
    template_name = "categories/list_categories.html"
    categories = Category.objects.filter()
    context = {"categories": categories}
    return render(request, template_name, context)


def edit_category(request, id_category):
    template_name = "categories/add_category.html"
    context = {}
    category = get_object_or_404(Category, id=id_category)

    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect("categories:list_categories")
    redirect("categories:list_categories")
    form = CategoryForm(instance=category)
    context["form"] = form
    return render(request, template_name, context)


def delete_category(request, id_category):
    category = Category.objects.get(id=id_category)
    category.delete()
    return redirect("categories:list_categories")


# teste

templates/categories/add_category.html
{% extends 'base.html' %}

{% block title %}
  Adicionar Categoria - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
  <b>Cadastro de Categoria</b>
  <br />
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    <label>Nome:</label>
    <br />
    {{ form.name }}
    <br />
    <br />
    <label>Descricao:</label>
    <br />
    {{ form.description }}
    <br />
    <br />
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

templates/categories/list_categories.html
{% extends 'base.html' %}

{% block title %}
  Lista de Categorias - {{ block.super }}
{% endblock %}

{% block body %}
   <br />
    <a href="{% url 'categories:add_category' %}">Cadastro de novo categoria</a>
  <br />
  <br />
  <b>Lista de Categorias</b>
  <br />
  <br />
  <table border="1">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Descricao</th>
        <th scope="col">Editar</th>
        <th scope="col">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <th>{{ category.id }}</th>
          <td>{{ category.name }}</td>
          <td>{{ category.description }}</td>
          <td>
            <a href="{% url 'categories:edit_category' category.id %}">Editar</a>
          </td>
          <td>
            <a href="{% url 'categories:delete_category' category.id %}" >Excluir</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}