apps/categories/urls.py
from django.urls import path
from . import views

app_name = "categories"

urlpatterns = [
    path("adicionar/", views.add_Category, name="add_category"),
    path("", views.list_categories, name="list_categories"),
    path("editar/<int:id_category>/", views.edit_category, name="edit_category"),
    path("excluir/<int:id_category>/", views.delete_category, name="delete_category"),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

apps/order/urls.py
from . import views
from django.urls import path


app_name = "orders"

urlpatterns = [
    path("adicionar/", views.add_orders, name="add_orders"),
    path("", views.list_orders, name="list_orders"),
    path("editar/<int:id_order>/", views.edit_orders, name="edit_orders"),
    path("excluir/<int:id_order>/", views.delete_orders, name="delete_orders"),
]

apps/product/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('adicionar/', views.add_products, name='add_products'),
    path("", views.list_products, name="list_products"),
    path("editar/<int:id_product>/", views.edit_products, name="edit_products"),
    path("excluir/<int:id_product>/", views.delete_products, name="delete_products"),
]

modeloapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("categorias/", include("categories.urls", namespace="categories")),
    path("produtos/", include("product.urls", namespace="products")),
    path("clientes/", include("clients.urls", namespace="clients")),
    path("pedidos/", include("order.urls", namespace="orders")),
    path('socialnetworks/', include('socialnetworks.urls', namespace="socialnetworks")),
    path('clientsocialnetworks/', include('clientsocialnetworks.urls', namespace="clientsocialnetworks")),
    path('orderitems/', include('orderitems.urls', namespace="orderitems")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/arquivo_com_estilos.css' %}">
    <title>{% block title %}Nome do meu App{% endblock title %}</title>
</head>
<body>
    
    <a href="{% url 'core:home' %}" ><img src="{% static 'img/menu.png' %}" width="200" height="60" /></a>
    <br />
    <a href="{% url 'categories:list_categories' %}" ><button onclick="mudarCor()">Categorias</button></a>
    <a href="{% url 'products:list_products' %}" ><button onclick="mudarCor()">Produtos</button></a>
    <a href="#" ><button onclick="alertarMensagem()">Clientes</button></a>
    <a href="{% url 'orders:list_orders' %}" ><button onclick="mudarCor()">Pedidos</button></a>
    <br />

    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/arquivo_com_javascript.js' %}"></script>
</body>
</html>