apps/order/urls.py
from . import views
from django.urls import path


app_name = "orders"

urlpatterns = [
    path("adicionar/", views.add_orders, name="add_orders"),
    path("", views.list_orders, name="list_orders"),
    path("editar/<int:id_order>/", views.edit_orders, name="edit_orders"),
    path("excluir/<int:id_order>/", views.delete_orders, name="delete_orders"),
]

modeloapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("categorias/", include("categories.urls", namespace="categories")),
    path("produtos/", include("product.urls", namespace="products")),
    path("clientes/", include("clients.urls", namespace="clients")),
    path("pedidos/", include("order.urls", namespace="orders")),
    path('socialnetworks/', include('socialnetworks.urls', namespace="socialnetworks")),
    path('clientsocialnetworks/', include('clientsocialnetworks.urls', namespace="clientsocialnetworks")),
    path('orderitems/', include('orderitems.urls', namespace="orderitems")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/models.py
from django.db import models
from clients.models import Client

# # Create your models here.

class Order(models.Model):
    total_price = models.FloatField('Preco Total', null=True, blank=True, default=0.0)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    #created_on = models.DateTimeField(auto_now_add=True) | Usa horario atual para preencher campo
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['-client__id']
        #ordering =['created_on'] | Opcao usando para ordernar por hora.

    def __str__(self):
        return "%s" % (self.total_price) 

apps/order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ()

apps/order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OrderForm
from .models import Order


def add_orders(request):
    template_name = 'order/add_orders.html'
    context = {}
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('orders:list_orders')
    form = OrderForm()
    context['form'] = form
    return render(request, template_name, context)


def list_orders(request):
    template_name = "order/list_orders.html"
    orders = Order.objects.filter()
    context = {"orders": orders}
    return render(request, template_name, context)



def edit_orders(request, id_order):
    template_name = "order/add_orders.html"
    context = {}
    order = get_object_or_404(Order, id=id_order)

    if request.method == "POST":
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect("orders:list_orders")
    form = OrderForm(instance=order)
    context["form"] = form
    return render(request, template_name, context)


def delete_orders(request, id_order):
    product = Order.objects.get(id=id_order)
    product.delete()
    return redirect("orders:list_orders")

templates/order/add_orders.html
{% extends 'base.html' %}

{% block title %}
  Adicionar Pedido - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
  <b>Cadastro de Pedido</b>
  <br />
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    <label>Preço total:</label>
    <br />
    {{ form.total_price }}
    <br />
    <br />
    <label>status:</label>
    <br />
    {{ form.status }}
    <br />
    <br />
    <label>Cliente:</label>
    <br />
    {{ form.client }}
    <br />
    <br />
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

templates/order/list_orders.html
{% extends 'base.html' %}

{% block title %}
  Lista de Pedidos - {{ block.super }}
{% endblock %}

{% block body %}
   <br />
    <a href="{% url 'orders:add_orders' %}">Cadastro de novo Pedido</a>
  <br />
  <br />
  <b>Lista de Pedidos</b>
  <br />
  <br />
  <table border="1">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Preço Total</th>
        <th scope="col">Situação do pedido</th>
        <th scope="col">Cliente</th>
        <th scope="col">Editar</th>
        <th scope="col">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <th>{{ order.id }}</th>
          <td>{{ order.total_price }}</td>
          <td>{{ order.get_status_display }}</td>
          <td>{{ order.client }}</td>
          <td>
            <a href="{% url 'orders:edit_orders' order.id %}">Editar</a>
          </td>
          <td>
            <a href="{% url 'orders:delete_orders' order.id %}" >Excluir</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}